name: build

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  run:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        php-versions: ['8.3', '8.4']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # just to be sure there is no other PHP-FPM installed
      - name: Uninstall default PHP
        run:  sudo apt purge php-common

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer:v2
        env:
          update: true

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run phpcs
        run: composer phpcs

      - name: Run phpstan
        run: composer phpstan

      - name: Install libfcgi0ldbl
        run: sudo apt install libfcgi0ldbl

      - name: Run phpfpm under user runner
        run: sudo sed -i 's/www-data/runner/g' /etc/php/${{ matrix.php-versions }}/fpm/pool.d/www.conf

      - name: Restart php-fpm
        run: sudo service php${{ matrix.php-versions }}-fpm restart

      - name: Run tests
        run: composer tests
